### PR TITLE
When generating an error, the name is taken first from "json" tag and then from the "form" tag

### PR DESCRIPTION
**Pull request by ghostiam**
Fix: If the field is hidden for output generation json ( `json:"-"`), but is available for bindings, if this field is required ( `binding:"required"`) and it is empty then the name will be specified in error "-" taken from tag "json", but not "form" tag.

### CODE REVIEW

**Comment by mholt** [comment]
Hey Vladislav, thanks for your PR! Can you add a test to ensure this works?

**Comment by GhostRussia** [comment]
OK, I'll write tests

**Comment by GhostRussia** [comment]
@mholt OK, I'll write tests

**Comment by GhostRussia** [comment]
@mholt I made a mistake in the description of the fix. Read the new description. I'm not sure that it needs the test.

**Comment by mholt** [comment]
Thanks, it looks like some tests are failing though.

**Comment by GhostRussia** [comment]
I do not know how to write a test to check the output generated by the error in the field with the real name of the field in the tag

**Pull request closed without merging**
